'use strict';

var async = require('async'),
    xml2js = require('xml2js');

module.exports = function (grunt) {

    var config = grunt.file.readJSON('one-config.json');

    grunt.registerTask('extract', 'Extract failed test cases from xml generated by AutoTester', function () {

        var results = {
            test_results: {
                queries: {
                    query: []
                }
            }
        };
        var failed, timeout, exception, crash;
        var finish = this.async();

        async.series([
            function (done) {
                //console.log('First');
                var files = grunt.file.expand(config.path.tests + '*.xml');
                var parser = new xml2js.Parser();

                files.forEach(function (file) {
                    parser.parseString(grunt.file.read(file), function (err, result) {
                        //console.dir(result.test_results.queries[0]);
                        result.test_results.queries[0].query.forEach(function (query) {
                            //console.dir(query);
                            results.test_results.queries.query.push(query);
                        });
                        //results.push(result.test_results.queries);
                    });
                });

                done();
            },
            function (done) {
                //console.log('Second');
                failed = JSON.parse(JSON.stringify(results));
                timeout = JSON.parse(JSON.stringify(results));
                exception = JSON.parse(JSON.stringify(results));
                crash = JSON.parse(JSON.stringify(results));

                async.parallel([
                        function (callback) {
                            for (var j = failed.test_results.queries.query.length; j--;) {
                                if (failed.test_results.queries.query[j].passed != undefined ||
                                    failed.test_results.queries.query[j].timeout != undefined ||
                                    failed.test_results.queries.query[j].exception != undefined ||
                                    failed.test_results.queries.query[j].crash != undefined) {
                                    failed.test_results.queries.query.splice(j, 1);
                                }
                            }
                            callback();
                        },
                        function (callback) {
                            for (var j = timeout.test_results.queries.query.length; j--;) {
                                if (timeout.test_results.queries.query[j].passed != undefined ||
                                    timeout.test_results.queries.query[j].failed != undefined ||
                                    timeout.test_results.queries.query[j].exception != undefined ||
                                    timeout.test_results.queries.query[j].crash != undefined) {
                                    timeout.test_results.queries.query.splice(j, 1);
                                }
                            }
                            callback();
                        },
                        function (callback) {
                            for (var j = exception.test_results.queries.query.length; j--;) {
                                if (exception.test_results.queries.query[j].passed != undefined ||
                                    exception.test_results.queries.query[j].failed != undefined ||
                                    exception.test_results.queries.query[j].timeout != undefined ||
                                    exception.test_results.queries.query[j].crash != undefined) {
                                    exception.test_results.queries.query.splice(j, 1);
                                }
                            }
                            callback();
                        },
                        function (callback) {
                            for (var j = crash.test_results.queries.query.length; j--;) {
                                if (crash.test_results.queries.query[j].passed != undefined ||
                                    crash.test_results.queries.query[j].failed != undefined ||
                                    crash.test_results.queries.query[j].timeout != undefined ||
                                    crash.test_results.queries.query[j].exception != undefined) {
                                    crash.test_results.queries.query.splice(j, 1);
                                }
                            }
                            callback();
                        }
                    ],
                    function (err, results) {
                        done();
                    });
            },
            function (done) {
                //console.log('Third');
                //console.dir(failed.test_results.queries.query);
                var builder = new xml2js.Builder();
                var xml = builder.buildObject(failed);
                //console.dir(xml);
                xml = '<?xml-stylesheet type="text/xsl" href="analysis.xsl"?>' + xml;
                xml = xml.replace('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>', '');
                grunt.file.write('tests/output/failed.xml', xml);


                async.parallel([
                        function (callback) {
                            var xml = builder.buildObject(failed);
                            xml = '<?xml-stylesheet type="text/xsl" href="analysis.xsl"?>' + xml;
                            xml = xml.replace('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>', '');
                            grunt.file.write(config.path.output + 'failed.xml', xml);
                            callback();
                        },
                        function (callback) {
                            var xml = builder.buildObject(timeout);
                            xml = '<?xml-stylesheet type="text/xsl" href="analysis.xsl"?>' + xml;
                            xml = xml.replace('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>', '');
                            grunt.file.write(config.path.output + 'timeout.xml', xml);
                            callback();
                        },
                        function (callback) {
                            var xml = builder.buildObject(exception);
                            xml = '<?xml-stylesheet type="text/xsl" href="analysis.xsl"?>' + xml;
                            xml = xml.replace('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>', '');
                            grunt.file.write(config.path.output + 'exception.xml', xml);
                            callback();
                        },
                        function (callback) {
                            var xml = builder.buildObject(crash);
                            xml = '<?xml-stylesheet type="text/xsl" href="analysis.xsl"?>' + xml;
                            xml = xml.replace('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>', '');
                            grunt.file.write(config.path.output + 'crash.xml', xml);
                            callback();
                        }
                    ],
                    function (err, results) {
                        done();
                    });
            }
        ], function (err, results) {
            finish();
        });


    });

};
