'use strict';

var async = require('async'),
    xml2js = require('xml2js');

module.exports = function (grunt) {

    grunt.registerTask('extract', 'Extract failed test cases from xml generated by AutoTester', function () {

        var results = {
            test_results: {
                queries: {
                    query: []
                }
            }
        };
        var failed;
        var crashed;
        var finish = this.async();

        async.series([
            function (done) {
                //console.log('First');
                var files = grunt.file.expand('tests/*.xml');
                var parser = new xml2js.Parser();

                files.forEach(function (file) {
                    parser.parseString(grunt.file.read(file), function (err, result) {
                        //console.dir(result.test_results.queries[0]);
                        result.test_results.queries[0].query.forEach(function (query) {
                            //console.dir(query);
                            results.test_results.queries.query.push(query);
                        });
                        //results.push(result.test_results.queries);
                    });
                });

                done();
            },
            function (done) {
                //console.log('Second');
                failed = results;

                for (var j = failed.test_results.queries.query.length; j--;) {
                    if (failed.test_results.queries.query[j].passed != undefined) {
                        failed.test_results.queries.query.splice(j, 1);
                    }
                }
                done();
            },
            function (done) {
                //console.log('Third');
                //console.dir(failed.test_results.queries.query);
                var builder = new xml2js.Builder();
                var xml = builder.buildObject(failed);
                //console.dir(xml);
                xml = '<?xml-stylesheet type="text/xsl" href="analysis.xsl"?>' + xml;
                xml = xml.replace('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>', '');
                grunt.file.write('tests/output/failed.xml', xml);
                done();
            }
        ], function (err, results) {
            finish();
        });


    });

};
